#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do
  desc 'Deploy a build for beta testing'
  lane :internal do
    match(
      type: "appstore",
      readonly: true
    )

    cocoapods(
      try_repo_update_on_error: true,
    )

    increment_build_number

    gym(
      workspace: 'RocketChatRN.xcworkspace',
      scheme: 'RocketChat',
      export_method: 'app-store',
      configuration: 'Release',
    )

    pilot
  end
end
