#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do

  desc 'Deploy a build for beta testing'
  lane :internal do
    match(
      type: "appstore",
      readonly: true
    )

    bootstrap_cocoapods

    gym(
      workspace: 'RocketChatRN.xcworkspace',
      scheme: 'RocketChat',
      export_method: 'app-store',
      configuration: 'Release',
    )

    pilot(
      distribute_external: true,
      beta_app_feedback_email: 'handhci@gmail.com',
      beta_app_description: 'Beta build for testing',
      changelog: 'Fixes and improvements',
      groups: 'Beta',
    )

  end

  desc 'Install cocoapods dependencies'
  lane :bootstrap_cocoapods do
    cocoapods(
      try_repo_update_on_error: true,
    )
  end

end
